/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 30
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__newline = 1,
  anon_sym_SLASH_STAR = 2,
  aux_sym_comment_token1 = 3,
  aux_sym_comment_token2 = 4,
  aux_sym_comment_token3 = 5,
  anon_sym_STAR_SLASH = 6,
  sym_annotation = 7,
  sym_block_label = 8,
  sym_action_verb = 9,
  anon_sym_each = 10,
  anon_sym_break = 11,
  sym_template_var = 12,
  sym_file_path = 13,
  anon_sym_u2192 = 14,
  anon_sym_EQ = 15,
  anon_sym_u00d7 = 16,
  sym_identifier = 17,
  sym_word = 18,
  sym_source_file = 19,
  sym__line = 20,
  sym_comment = 21,
  sym_block_label_line = 22,
  sym_statement = 23,
  sym__token = 24,
  sym_control_keyword = 25,
  sym_operator = 26,
  aux_sym_source_file_repeat1 = 27,
  aux_sym_comment_repeat1 = 28,
  aux_sym_block_label_line_repeat1 = 29,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__newline] = "_newline",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [aux_sym_comment_token2] = "comment_token2",
  [aux_sym_comment_token3] = "comment_token3",
  [anon_sym_STAR_SLASH] = "*/",
  [sym_annotation] = "annotation",
  [sym_block_label] = "block_label",
  [sym_action_verb] = "action_verb",
  [anon_sym_each] = "each",
  [anon_sym_break] = "break",
  [sym_template_var] = "template_var",
  [sym_file_path] = "file_path",
  [anon_sym_u2192] = "\u2192",
  [anon_sym_EQ] = "=",
  [anon_sym_u00d7] = "\u00d7",
  [sym_identifier] = "identifier",
  [sym_word] = "word",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_comment] = "comment",
  [sym_block_label_line] = "block_label_line",
  [sym_statement] = "statement",
  [sym__token] = "_token",
  [sym_control_keyword] = "control_keyword",
  [sym_operator] = "operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
  [aux_sym_block_label_line_repeat1] = "block_label_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__newline] = sym__newline,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [aux_sym_comment_token3] = aux_sym_comment_token3,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym_annotation] = sym_annotation,
  [sym_block_label] = sym_block_label,
  [sym_action_verb] = sym_action_verb,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_break] = anon_sym_break,
  [sym_template_var] = sym_template_var,
  [sym_file_path] = sym_file_path,
  [anon_sym_u2192] = anon_sym_u2192,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_u00d7] = anon_sym_u00d7,
  [sym_identifier] = sym_identifier,
  [sym_word] = sym_word,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_comment] = sym_comment,
  [sym_block_label_line] = sym_block_label_line,
  [sym_statement] = sym_statement,
  [sym__token] = sym__token,
  [sym_control_keyword] = sym_control_keyword,
  [sym_operator] = sym_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
  [aux_sym_block_label_line_repeat1] = aux_sym_block_label_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_block_label] = {
    .visible = true,
    .named = true,
  },
  [sym_action_verb] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [sym_template_var] = {
    .visible = true,
    .named = true,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_u2192] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u00d7] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_word] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_label_line] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_control_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_label_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      ADVANCE_MAP(
        '\n', 12,
        '*', 34,
        '.', 44,
        '/', 17,
        '=', 31,
        'b', 41,
        'e', 35,
        '{', 7,
        '}', 8,
        0xd7, 32,
        0x2192, 30,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('-' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 12,
        '.', 44,
        '=', 31,
        'b', 41,
        'e', 35,
        '{', 7,
        '}', 8,
        0xd7, 32,
        0x2192, 30,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(9);
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead)) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(19);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '{') ADVANCE(8);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(29);
      if (('-' <= lookahead && lookahead <= '9') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(29);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(3);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\n') ADVANCE(12);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '(' || '*' < lookahead) &&
          lookahead != '/') ADVANCE(14);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_comment_token3);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_annotation);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_block_label);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_action_verb);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_action_verb);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_each);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_break);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_template_var);
      if (lookahead == '/') ADVANCE(29);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(8);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(27);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead == '/') ADVANCE(29);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(29);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_file_path);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= '{') ||
          lookahead == '}') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_u2192);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_u00d7);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(45);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'a') ADVANCE(40);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'c') ADVANCE(39);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'e') ADVANCE(36);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'h') ADVANCE(23);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'k') ADVANCE(24);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == 'r') ADVANCE(38);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == ':') ADVANCE(33);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead == '-' ||
          lookahead == '.') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_word);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(27);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 10},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [aux_sym_comment_token3] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [sym_template_var] = ACTIONS(1),
    [sym_file_path] = ACTIONS(1),
    [anon_sym_u2192] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_u00d7] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_word] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym__line] = STATE(7),
    [sym_comment] = STATE(7),
    [sym_block_label_line] = STATE(7),
    [sym_statement] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(7),
    [sym_block_label] = ACTIONS(9),
    [sym_action_verb] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      sym__newline,
    ACTIONS(15), 2,
      anon_sym_each,
      anon_sym_break,
    ACTIONS(17), 2,
      sym_template_var,
      sym_word,
    ACTIONS(19), 2,
      sym_file_path,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
    STATE(5), 4,
      sym__token,
      sym_control_keyword,
      sym_operator,
      aux_sym_block_label_line_repeat1,
  [27] = 6,
    ACTIONS(23), 1,
      sym__newline,
    ACTIONS(15), 2,
      anon_sym_each,
      anon_sym_break,
    ACTIONS(25), 2,
      sym_template_var,
      sym_word,
    ACTIONS(27), 2,
      sym_file_path,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
    STATE(4), 4,
      sym__token,
      sym_control_keyword,
      sym_operator,
      aux_sym_block_label_line_repeat1,
  [54] = 6,
    ACTIONS(29), 1,
      sym__newline,
    ACTIONS(15), 2,
      anon_sym_each,
      anon_sym_break,
    ACTIONS(31), 2,
      sym_template_var,
      sym_word,
    ACTIONS(33), 2,
      sym_file_path,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
    STATE(6), 4,
      sym__token,
      sym_control_keyword,
      sym_operator,
      aux_sym_block_label_line_repeat1,
  [81] = 6,
    ACTIONS(35), 1,
      sym__newline,
    ACTIONS(15), 2,
      anon_sym_each,
      anon_sym_break,
    ACTIONS(31), 2,
      sym_template_var,
      sym_word,
    ACTIONS(33), 2,
      sym_file_path,
      sym_identifier,
    ACTIONS(21), 3,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
    STATE(6), 4,
      sym__token,
      sym_control_keyword,
      sym_operator,
      aux_sym_block_label_line_repeat1,
  [108] = 6,
    ACTIONS(37), 1,
      sym__newline,
    ACTIONS(39), 2,
      anon_sym_each,
      anon_sym_break,
    ACTIONS(42), 2,
      sym_template_var,
      sym_word,
    ACTIONS(45), 2,
      sym_file_path,
      sym_identifier,
    ACTIONS(48), 3,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
    STATE(6), 4,
      sym__token,
      sym_control_keyword,
      sym_operator,
      aux_sym_block_label_line_repeat1,
  [135] = 6,
    ACTIONS(7), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_block_label,
    ACTIONS(11), 1,
      sym_action_verb,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(53), 1,
      sym__newline,
    STATE(9), 5,
      sym__line,
      sym_comment,
      sym_block_label_line,
      sym_statement,
      aux_sym_source_file_repeat1,
  [158] = 2,
    ACTIONS(57), 4,
      anon_sym_each,
      anon_sym_break,
      sym_template_var,
      sym_word,
    ACTIONS(55), 6,
      sym__newline,
      sym_file_path,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
      sym_identifier,
  [173] = 6,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym__newline,
    ACTIONS(64), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(67), 1,
      sym_block_label,
    ACTIONS(70), 1,
      sym_action_verb,
    STATE(9), 5,
      sym__line,
      sym_comment,
      sym_block_label_line,
      sym_statement,
      aux_sym_source_file_repeat1,
  [196] = 2,
    ACTIONS(75), 4,
      anon_sym_each,
      anon_sym_break,
      sym_template_var,
      sym_word,
    ACTIONS(73), 6,
      sym__newline,
      sym_file_path,
      anon_sym_u2192,
      anon_sym_EQ,
      anon_sym_u00d7,
      sym_identifier,
  [211] = 4,
    ACTIONS(77), 1,
      aux_sym_comment_token1,
    ACTIONS(81), 1,
      anon_sym_STAR_SLASH,
    STATE(12), 1,
      aux_sym_comment_repeat1,
    ACTIONS(79), 3,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
      sym_annotation,
  [226] = 4,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(87), 1,
      anon_sym_STAR_SLASH,
    STATE(13), 1,
      aux_sym_comment_repeat1,
    ACTIONS(85), 3,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
      sym_annotation,
  [241] = 4,
    ACTIONS(89), 1,
      aux_sym_comment_token1,
    ACTIONS(95), 1,
      anon_sym_STAR_SLASH,
    STATE(13), 1,
      aux_sym_comment_repeat1,
    ACTIONS(92), 3,
      aux_sym_comment_token2,
      aux_sym_comment_token3,
      sym_annotation,
  [256] = 2,
    ACTIONS(99), 1,
      sym_action_verb,
    ACTIONS(97), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_SLASH_STAR,
      sym_block_label,
  [266] = 2,
    ACTIONS(103), 1,
      sym_action_verb,
    ACTIONS(101), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_SLASH_STAR,
      sym_block_label,
  [276] = 2,
    ACTIONS(107), 1,
      sym_action_verb,
    ACTIONS(105), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_SLASH_STAR,
      sym_block_label,
  [286] = 2,
    ACTIONS(111), 1,
      sym_action_verb,
    ACTIONS(109), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_SLASH_STAR,
      sym_block_label,
  [296] = 2,
    ACTIONS(115), 1,
      sym_action_verb,
    ACTIONS(113), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_SLASH_STAR,
      sym_block_label,
  [306] = 2,
    ACTIONS(119), 1,
      sym_action_verb,
    ACTIONS(117), 4,
      ts_builtin_sym_end,
      sym__newline,
      anon_sym_SLASH_STAR,
      sym_block_label,
  [316] = 1,
    ACTIONS(121), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 27,
  [SMALL_STATE(4)] = 54,
  [SMALL_STATE(5)] = 81,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 135,
  [SMALL_STATE(8)] = 158,
  [SMALL_STATE(9)] = 173,
  [SMALL_STATE(10)] = 196,
  [SMALL_STATE(11)] = 211,
  [SMALL_STATE(12)] = 226,
  [SMALL_STATE(13)] = 241,
  [SMALL_STATE(14)] = 256,
  [SMALL_STATE(15)] = 266,
  [SMALL_STATE(16)] = 276,
  [SMALL_STATE(17)] = 286,
  [SMALL_STATE(18)] = 296,
  [SMALL_STATE(19)] = 306,
  [SMALL_STATE(20)] = 316,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_label_line_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_label_line_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_label_line_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_label_line_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_label_line_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_control_keyword, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_control_keyword, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [92] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_label_line, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_label_line, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_label_line, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_label_line, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_prosaic(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "prosaic",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
