[changelog]
header = """# Changelog

Format: [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).\n
Versioning: [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/andjones/kdb
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] — {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim }}
    {% for commit in commits %}
        - {{ commit.message | split(pat="\n") | first | trim }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^refactor", group = "Changed" },
    { message = "^chore", group = "Changed" },
    { message = "^docs", group = "Docs" },
    { message = "^test", group = "Testing" },
    { message = "^bump version", skip = true },
    { body = ".*", group = "Other" },
]
tag_pattern = "v[0-9].*"
sort_commits = "oldest"
