//! DB → markdown materialization.
//!
//! Writes per-project `TODO.md` files at `<project.path>/.tasks/TODO.md`.
//! Files are regenerated from the DB and should not be edited by hand.

use anyhow::{Context, Result};
use chrono::Utc;
use rusqlite::Connection;
use std::fs;
use std::path::{Path, PathBuf};

use crate::projects::{self, Project};
use crate::tasks::{self, ListFilters, TaskView};

/// Subdir under each project's path where the materialized file lives.
const TASKS_DIR: &str = ".tasks";
const TODO_FILE: &str = "TODO.md";

/// Header inserted at the top of every generated file.
const GENERATED_NOTE: &str = "_Generated by `kdb`. Do not edit by hand._";

/// Counts of tasks per status for a single project.
#[derive(Debug, Default)]
struct Counts {
    open: usize,
    in_progress: usize,
    parked: usize,
    done: usize,
}

/// Write the materialized TODO for a single project.
///
/// Returns the path written.
pub fn materialize_project(
    conn: &Connection,
    root: &Path,
    slug: &str,
) -> Result<PathBuf> {
    let project = projects::get_by_slug(conn, slug)?
        .with_context(|| format!("project not found: {slug}"))?;
    materialize(conn, root, &project)
}

/// Write materialized TODO files for every non-archived project.
pub fn materialize_all(conn: &Connection, root: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for project in projects::list(conn, false)? {
        let path = materialize(conn, root, &project)?;
        out.push(path);
    }
    Ok(out)
}

fn materialize(
    conn: &Connection,
    root: &Path,
    project: &Project,
) -> Result<PathBuf> {
    let top_n = read_top_n(conn)?;
    let in_progress = tasks::list(
        conn,
        ListFilters {
            statuses: Some(&["in_progress"]),
            project_slug: Some(&project.slug),
            ..Default::default()
        },
    )?;
    let open = tasks::list(
        conn,
        ListFilters {
            statuses: Some(&["open"]),
            project_slug: Some(&project.slug),
            limit: Some(top_n),
            ..Default::default()
        },
    )?;
    let counts = count_by_status(conn, &project.slug)?;

    let body = render(project, &in_progress, &open, &counts, top_n);

    let out_dir = root.join(&project.path).join(TASKS_DIR);
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;
    let out_path = out_dir.join(TODO_FILE);
    fs::write(&out_path, body)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(out_path)
}

fn read_top_n(conn: &Connection) -> Result<i64> {
    let raw: Option<String> = conn
        .query_row(
            "SELECT value FROM meta WHERE key = 'top_n'",
            [],
            |row| row.get(0),
        )
        .map(Some)
        .or_else(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => Ok(None),
            other => Err(other),
        })
        .context("failed to read meta.top_n")?;
    raw.as_deref()
        .map(str::parse::<i64>)
        .transpose()
        .context("meta.top_n is not an integer")
        .map(|v| v.unwrap_or(10))
}

fn count_by_status(conn: &Connection, slug: &str) -> Result<Counts> {
    let mut stmt = conn.prepare(
        "SELECT t.status, COUNT(*) FROM tasks t \
         JOIN projects p ON p.id = t.project_id \
         WHERE p.slug = ? GROUP BY t.status",
    )?;
    let rows = stmt.query_map([slug], |row| {
        let status: String = row.get(0)?;
        let count: i64 = row.get(1)?;
        Ok((status, count as usize))
    })?;
    let mut counts = Counts::default();
    for row in rows {
        let (status, n) = row?;
        match status.as_str() {
            "open" => counts.open = n,
            "in_progress" => counts.in_progress = n,
            "parked" => counts.parked = n,
            "done" => counts.done = n,
            _ => {}
        }
    }
    Ok(counts)
}

fn render(
    project: &Project,
    in_progress: &[TaskView],
    open: &[TaskView],
    counts: &Counts,
    top_n: i64,
) -> String {
    let mut out = String::new();
    let updated = Utc::now().format("%Y-%m-%dT%H:%M:%SZ");

    out.push_str("---\n");
    out.push_str(&format!("project: {}\n", project.slug));
    out.push_str(&format!("path: {}\n", project.path));
    out.push_str(&format!("updated: {updated}\n"));
    out.push_str("generated_by: kdb\n");
    out.push_str("---\n\n");

    out.push_str(&format!("# {} — TODO\n\n", project.slug));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n\n");

    out.push_str("## In progress\n\n");
    if in_progress.is_empty() {
        out.push_str("_(none)_\n\n");
    } else {
        for t in in_progress {
            out.push_str(&format_task_line(t));
        }
        out.push('\n');
    }

    let header = if counts.open > open.len() {
        format!("## Open (top {} of {})\n\n", open.len(), counts.open)
    } else {
        format!("## Open ({})\n\n", counts.open)
    };
    out.push_str(&header);
    if open.is_empty() {
        out.push_str("_(none)_\n\n");
    } else {
        for t in open {
            out.push_str(&format_task_line(t));
        }
        out.push('\n');
    }

    out.push_str("## Counts\n\n");
    out.push_str(&format!(
        "- open: {}\n- in_progress: {}\n- parked: {}\n- done: {}\n\n",
        counts.open, counts.in_progress, counts.parked, counts.done,
    ));

    out.push_str("## Commands\n\n");
    out.push_str(&format!(
        "- `kdb tasks list -P {slug}` — full list\n\
         - `kdb tasks add \"title\" -P {slug}` — add a task\n\
         - `kdb tasks show <id>` — view a task\n",
        slug = project.slug,
    ));

    let _ = top_n;
    out
}

fn format_task_line(t: &TaskView) -> String {
    let glyph = match t.task.status.as_str() {
        "in_progress" => "[~]",
        "open" => "[ ]",
        "done" => "[x]",
        "parked" => "[=]",
        _ => "[?]",
    };
    format!(
        "- {glyph} `{}` {} _(p{})_\n",
        t.external_id(),
        t.task.title,
        t.task.priority,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;
    use crate::project::root::ROOT_MARKER;
    use crate::projects::{self as projects_mod, AddArgs as ProjAddArgs};
    use crate::tasks::{self as tasks_mod, AddArgs as TaskAddArgs};
    use tempfile::TempDir;

    fn setup() -> (TempDir, Connection) {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir(tmp.path().join(ROOT_MARKER)).unwrap();
        let conn = db::open(tmp.path()).unwrap();
        (tmp, conn)
    }

    #[test]
    fn materialize_writes_todo_file() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                name: None,
                path: "projects/kdb",
                description: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "first",
                body: None,
                priority: Some(1),
                cycle_id: None,
                parent_id: None,
            },
        )
        .unwrap();

        let out = materialize_project(&conn, tmp.path(), "kdb").unwrap();
        assert!(out.exists());
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("# kdb — TODO"));
        assert!(body.contains("kdb-1"));
        assert!(body.contains("first"));
        assert!(body.contains("open: 1"));
    }

    #[test]
    fn top_n_truncates_open_list() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                name: None,
                path: "projects/kdb",
                description: None,
            },
        )
        .unwrap();
        conn.execute(
            "UPDATE meta SET value = '2' WHERE key = 'top_n'",
            [],
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        for i in 0..5 {
            tasks_mod::add(
                &mut conn,
                TaskAddArgs {
                    project_id: p.id,
                    title: &format!("t{i}"),
                    body: None,
                    priority: None,
                    cycle_id: None,
                    parent_id: None,
                },
            )
            .unwrap();
        }

        let out = materialize_project(&conn, tmp.path(), "kdb").unwrap();
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("Open (top 2 of 5)"));
    }
}
