//! DB → markdown materialization.
//!
//! Writes a per-project `index.md` plus one `T-{seq:04d}.md` file per
//! materialized task under `<project.path>/.tasks/`. The external task
//! id uses the project alias (e.g. `HRM-0120`) but the on-disk file is
//! project-local (`T-0120.md`), so the index sorts above the task
//! files alphabetically. Files are regenerated from the DB and should
//! not be edited by hand; stale task files (no longer in the DB) are
//! removed. `TODO.md` and other hand-written notes are left alone.

use anyhow::{Context, Result};
use chrono::Utc;
use rusqlite::Connection;
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use crate::projects::{self, Project};
use crate::tasks::{self, ListFilters, TaskView};

/// Subdir under each project's path where materialized files live.
const TASKS_DIR: &str = ".tasks";
const INDEX_FILE: &str = "index.md";

/// Header inserted at the top of every generated file.
const GENERATED_NOTE: &str = "_Generated by `kdb`. Do not edit by hand._";

/// Counts of tasks per status for a single project.
#[derive(Debug, Default)]
struct Counts {
    open: usize,
    in_progress: usize,
    parked: usize,
    done: usize,
}

/// Write the materialized index and per-task files for a single project.
///
/// Returns the path of the written index.md.
pub fn materialize_project(
    conn: &Connection,
    root: &Path,
    slug: &str,
    limit: Option<i64>,
) -> Result<PathBuf> {
    let project = projects::get_by_slug(conn, slug)?
        .with_context(|| format!("project not found: {slug}"))?;
    materialize(conn, root, &project, limit)
}

/// Write materialized files for every non-archived project.
pub fn materialize_all(
    conn: &Connection,
    root: &Path,
    limit: Option<i64>,
) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    for project in projects::list(conn, false)? {
        let path = materialize(conn, root, &project, limit)?;
        out.push(path);
    }
    Ok(out)
}

fn materialize(
    conn: &Connection,
    root: &Path,
    project: &Project,
    limit: Option<i64>,
) -> Result<PathBuf> {
    let out_dir = root.join(&project.path).join(TASKS_DIR);
    fs::create_dir_all(&out_dir)
        .with_context(|| format!("failed to create {}", out_dir.display()))?;

    // Full task list: used for index counts and the open/in_progress split.
    let all = tasks::list(
        conn,
        ListFilters {
            statuses: Some(&["open", "in_progress", "done", "parked"]),
            project_slug: Some(&project.slug),
            ..Default::default()
        },
    )?;

    let top_n = limit.unwrap_or_else(|| read_top_n(conn).unwrap_or(10));
    let in_progress: Vec<TaskView> = all
        .iter()
        .filter(|t| t.task.status == "in_progress")
        .cloned()
        .collect();
    let open_full: Vec<TaskView> = all
        .iter()
        .filter(|t| t.task.status == "open")
        .cloned()
        .collect();
    let mut open_top = open_full.clone();
    if top_n >= 0 {
        open_top.truncate(top_n as usize);
    }

    // Materialize task files for active work only: all in_progress + top-N
    // open. Done and parked show up in the counts but aren't written out as
    // separate files (they'd just clutter the directory).
    let mut expected: HashSet<String> = HashSet::new();
    for t in in_progress.iter().chain(open_top.iter()) {
        let name = task_file_name(t.task.seq);
        let task_path = out_dir.join(&name);
        fs::write(&task_path, render_task_file(project, t))
            .with_context(|| format!("failed to write {}", task_path.display()))?;
        expected.insert(name);
    }
    clean_stale_task_files(&out_dir, &expected)?;

    let parked: Vec<TaskView> = all
        .iter()
        .filter(|t| t.task.status == "parked")
        .cloned()
        .collect();
    let counts = count_by_status(&all);
    let body = render_index(
        project,
        &in_progress,
        &open_top,
        &parked,
        &counts,
        open_full.len(),
    );
    let out_path = out_dir.join(INDEX_FILE);
    fs::write(&out_path, body)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    Ok(out_path)
}

fn read_top_n(conn: &Connection) -> Result<i64> {
    let raw: Option<String> = conn
        .query_row(
            "SELECT value FROM meta WHERE key = 'top_n'",
            [],
            |row| row.get(0),
        )
        .map(Some)
        .or_else(|e| match e {
            rusqlite::Error::QueryReturnedNoRows => Ok(None),
            other => Err(other),
        })
        .context("failed to read meta.top_n")?;
    raw.as_deref()
        .map(str::parse::<i64>)
        .transpose()
        .context("meta.top_n is not an integer")
        .map(|v| v.unwrap_or(10))
}

fn count_by_status(all: &[TaskView]) -> Counts {
    let mut counts = Counts::default();
    for t in all {
        match t.task.status.as_str() {
            "open" => counts.open += 1,
            "in_progress" => counts.in_progress += 1,
            "parked" => counts.parked += 1,
            "done" => counts.done += 1,
            _ => {}
        }
    }
    counts
}

fn render_index(
    project: &Project,
    in_progress: &[TaskView],
    open_top: &[TaskView],
    parked: &[TaskView],
    counts: &Counts,
    open_total: usize,
) -> String {
    let mut out = String::new();
    let updated = Utc::now().format("%Y-%m-%dT%H:%M:%SZ");

    out.push_str("---\n");
    out.push_str(&format!("project: {}\n", project.slug));
    out.push_str(&format!("alias: {}\n", project.alias));
    out.push_str(&format!(
        "path: {}/{TASKS_DIR}/{INDEX_FILE}\n",
        project.path,
    ));
    out.push_str(&format!("updated: {updated}\n"));
    out.push_str("generated_by: kdb\n");
    out.push_str("---\n\n");

    out.push_str(&format!("# {} — Tasks\n\n", project.slug));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n\n");

    out.push_str(&format!("## In progress ({})\n\n", counts.in_progress));
    push_table(&mut out, in_progress, /* link */ true);

    let header = if open_total > open_top.len() {
        format!("## Open (top {} of {})\n\n", open_top.len(), open_total)
    } else {
        format!("## Open ({open_total})\n\n")
    };
    out.push_str(&header);
    push_table(&mut out, open_top, true);

    out.push_str(&format!("## Parked ({})\n\n", counts.parked));
    // Parked files aren't materialized, so don't link to them.
    push_table(&mut out, parked, false);

    out.push_str(&format!("## Done ({})\n\n", counts.done));
    out.push_str(&format!(
        "_`kdb tasks list -P {slug} -s done`_\n\n",
        slug = project.slug,
    ));

    out.push_str("## Commands\n\n");
    out.push_str(&format!(
        "- `kdb tasks list -P {slug}` — full list\n\
         - `kdb tasks add \"title\" -P {slug}` — add a task\n\
         - `kdb tasks show <id>` — view a task\n",
        slug = project.slug,
    ));

    out
}

/// Append a `| Task | Title | Cycle | p |` markdown table for the tasks
/// (or an `_(none)_` line if empty). When `link` is true, the Task cell
/// is a markdown link to the task's materialized file.
fn push_table(out: &mut String, tasks: &[TaskView], link: bool) {
    if tasks.is_empty() {
        out.push_str("_(none)_\n\n");
        return;
    }
    out.push_str("| Task | Title | Cycle | p |\n");
    out.push_str("|---|---|---|---|\n");
    for t in tasks {
        let id = t.external_id();
        let task_cell = if link {
            format!("[{id}]({})", task_file_name(t.task.seq))
        } else {
            format!("`{id}`")
        };
        let cycle = t.cycle_key.as_deref().unwrap_or("—");
        let title = escape_md_cell(&t.task.title);
        out.push_str(&format!(
            "| {task_cell} | {title} | {cycle} | {pri} |\n",
            pri = t.task.priority,
        ));
    }
    out.push('\n');
}

/// On-disk name for a task's materialized file: `T-{seq:04d}.md`.
///
/// The file is project-local (lives inside `<project.path>/.tasks/`),
/// so the project alias isn't needed in the filename. Using `T-` keeps
/// `index.md` sorting above the task files alphabetically.
fn task_file_name(seq: i64) -> String {
    format!("T-{seq:04}.md")
}

fn escape_md_cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}

/// Render a single-task file: frontmatter + body, matching the old
/// hand-written `T-NNNN.md` shape.
fn render_task_file(project: &Project, t: &TaskView) -> String {
    let id = t.external_id();
    let file_name = task_file_name(t.task.seq);
    let mut out = String::new();
    out.push_str("---\n");
    out.push_str(&format!("id: {id}\n"));
    out.push_str(&format!("title: {}\n", yaml_scalar(&t.task.title)));
    out.push_str(&format!("status: {}\n", t.task.status));
    out.push_str(&format!("priority: {}\n", t.task.priority));
    out.push_str(&format!("project: {}\n", project.slug));
    if let Some(c) = &t.cycle_key {
        out.push_str(&format!("cycle: {c}\n"));
    }
    out.push_str(&format!("path: {}/{TASKS_DIR}/{file_name}\n", project.path));
    out.push_str(&format!("created_at: {}\n", t.task.created_at));
    out.push_str(&format!("updated_at: {}\n", t.task.updated_at));
    if let Some(closed) = &t.task.closed_at {
        out.push_str(&format!("closed_at: {closed}\n"));
    }
    out.push_str("generated_by: kdb\n");
    out.push_str("---\n\n");

    out.push_str(&format!("# {id} — {}\n\n", t.task.title));
    out.push_str(GENERATED_NOTE);
    out.push_str("\n");

    if let Some(body) = &t.task.body {
        let trimmed = body.trim_start_matches('\n');
        if !trimmed.is_empty() {
            out.push('\n');
            out.push_str(trimmed);
            if !out.ends_with('\n') {
                out.push('\n');
            }
        }
    }
    out
}

/// Wrap a scalar in double quotes if it contains yaml-significant chars.
fn yaml_scalar(s: &str) -> String {
    if s.contains([':', '#', '"', '\'', '\n'])
        || s.starts_with([' ', '-', '[', '{', '&', '*', '|', '>', '!', '%', '?'])
        || s.trim() != s
    {
        let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        s.to_string()
    }
}

/// Delete `T-NNNN.md` files that no longer correspond to a row in the
/// DB. Only the exact pattern (uppercase `T-`, all-digit stem, `.md`
/// suffix) is touched; TODO.md and other hand-written notes are left
/// alone.
fn clean_stale_task_files(
    dir: &Path,
    expected: &HashSet<String>,
) -> Result<()> {
    const PREFIX: &str = "T-";
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return Ok(()),
    };
    for entry in entries {
        let entry = entry?;
        let name = match entry.file_name().into_string() {
            Ok(n) => n,
            Err(_) => continue,
        };
        if !name.starts_with(PREFIX) || !name.ends_with(".md") {
            continue;
        }
        let stem = &name[PREFIX.len()..name.len() - 3];
        if !stem.chars().all(|c| c.is_ascii_digit()) || stem.is_empty() {
            continue;
        }
        if !expected.contains(&name) {
            fs::remove_file(entry.path()).with_context(|| {
                format!("failed to remove stale task file {}", entry.path().display())
            })?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db;
    use crate::project::root::ROOT_MARKER;
    use crate::projects::{self as projects_mod, AddArgs as ProjAddArgs};
    use crate::tasks::{self as tasks_mod, AddArgs as TaskAddArgs};
    use tempfile::TempDir;

    fn setup() -> (TempDir, Connection) {
        let tmp = TempDir::new().unwrap();
        std::fs::create_dir(tmp.path().join(ROOT_MARKER)).unwrap();
        let conn = db::open(tmp.path()).unwrap();
        (tmp, conn)
    }

    #[test]
    fn materialize_writes_todo_and_per_task() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "first",
                body: Some("## Goal\n\nDo the thing.\n"),
                priority: Some(1),
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
            },
        )
        .unwrap();

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        assert!(out.exists());
        assert!(out.ends_with("index.md"));
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("# kdb — Tasks"));
        assert!(body.contains("KDB-0001"));
        assert!(body.contains("(T-0001.md)"));
        assert!(body.contains("## Open (1)"));

        let task_file = tmp.path().join("projects/kdb/.tasks/T-0001.md");
        assert!(task_file.exists());
        let task_body = std::fs::read_to_string(&task_file).unwrap();
        assert!(task_body.contains("id: KDB-0001"));
        assert!(task_body.contains("title: first"));
        assert!(task_body.contains("Do the thing"));
    }

    #[test]
    fn stale_task_files_are_cleaned() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
            },
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        tasks_mod::add(
            &mut conn,
            TaskAddArgs {
                project_id: p.id,
                title: "keep",
                body: None,
                priority: None,
                cycle_id: None,
                parent_id: None,
                seq: None,
                status: None,
            },
        )
        .unwrap();

        let tasks_dir = tmp.path().join("projects/kdb/.tasks");
        std::fs::create_dir_all(&tasks_dir).unwrap();
        // Pre-seed a stale file that should be deleted.
        std::fs::write(tasks_dir.join("T-9999.md"), "stale").unwrap();
        // And unrelated files that should NOT be deleted.
        std::fs::write(tasks_dir.join("README.md"), "keep me").unwrap();
        std::fs::write(tasks_dir.join("TODO.md"), "user notes").unwrap();

        materialize_project(&conn, tmp.path(), "kdb", None).unwrap();

        assert!(!tasks_dir.join("T-9999.md").exists());
        assert!(tasks_dir.join("T-0001.md").exists());
        assert!(tasks_dir.join("README.md").exists());
        assert!(tasks_dir.join("TODO.md").exists());
    }

    #[test]
    fn top_n_truncates_open_list() {
        let (tmp, mut conn) = setup();
        projects_mod::add(
            &conn,
            ProjAddArgs {
                slug: "kdb",
                alias: "KDB",
                name: None,
                path: "projects/kdb",
                description: None,
            },
        )
        .unwrap();
        conn.execute(
            "UPDATE meta SET value = '2' WHERE key = 'top_n'",
            [],
        )
        .unwrap();
        let p = projects_mod::get_by_slug(&conn, "kdb").unwrap().unwrap();
        for i in 0..5 {
            tasks_mod::add(
                &mut conn,
                TaskAddArgs {
                    project_id: p.id,
                    title: &format!("t{i}"),
                    body: None,
                    priority: None,
                    cycle_id: None,
                    parent_id: None,
                    seq: None,
                    status: None,
                },
            )
            .unwrap();
        }

        let out = materialize_project(&conn, tmp.path(), "kdb", None).unwrap();
        let body = std::fs::read_to_string(&out).unwrap();
        assert!(body.contains("Open (top 2 of 5)"));
    }
}
